name: Build AppImage Camera Server Packages

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
      - 'README.md'

jobs:
  appimages_amd64:
    name: (x64) Camera Server AppImages
    runs-on: [x64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    timeout-minutes: 15

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Clean and Buf
      run: make clean-all buf
      env:
        BUF_TOKEN: '${{ secrets.BUF_TOKEN }}'

    - name: Build
      run: make appimages

    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Upload Files
      uses: google-github-actions/upload-cloud-storage@v0.5.0
      with:
        headers: "Cache-Control: no-cache"
        path: 'packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/camera-servers/'
        glob: '*'
        parent: false
        gzip: false

  appimages_arm64:
    name: (arm64) Camera Server AppImages
    runs-on: [arm64, qemu-host]
    container:
      image: ghcr.io/viamrobotics/canon:arm64-cache
      options: --platform linux/arm64
    timeout-minutes: 15

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Clean and Buf
      run: make clean-all buf
      env:
        BUF_TOKEN: '${{ secrets.BUF_TOKEN }}'

    - name: Build
      run: make appimages

    - name: Authorize GCP Upload
      uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Upload Files
      uses: google-github-actions/upload-cloud-storage@v0.5.0
      with:
        headers: "Cache-Control: no-cache"
        path: 'packaging/appimages/deploy/'
        destination: 'packages.viam.com/apps/camera-servers/'
        glob: '*'
        parent: false
        gzip: false
